GET http://localhost:5074/games

###
GET http://localhost:5074/games/1

###
POST http://localhost:5074/games
Content-Type:application/json

{
    "name": "Super Mario",
    "genreId": "3",
    "price": 69.99,
    "releaseDate": "2023-02-20"
}

###
POST http://localhost:5074/games
Content-Type:application/json

{
    "name": "Street Fighter II",
    "genreId": "1",
    "price": 20.99,
    "releaseDate": "2023-02-21"
}

###
POST http://localhost:5074/games
Content-Type:application/json

{
    "name": "Test game",
    "genreId": "1",
    "price": 20.99,
    "releaseDate": "2023-02-21"
}

###
PUT http://localhost:5074/games/8
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": "Action",
    "price": 21.99,
    "releaseDate": "2024-10-19"
  }

###
PUT http://localhost:5074/games/2
Content-Type:application/json

{
    "name": "Final Fantasy",
    "genreId": "1",
    "price": 20.99,
    "releaseDate": "2023-01-21"
}
###
DELETE http://localhost:5074/games/4
